### ISSUE TITLE
Avoid `Default::default` on structs when doing comparison by storing default values as static

### ISSUE THREAD

**Issue by 0x1991babe** [0x1991babe/kafka-protocol-rs#2]
Currently, comparisons during encoding refer to a `Default::default` value for a struct to determine whether they should be serialized or not. This causes lots of unnecessary allocations. Because we are using the default value as a zero value for comparison, we should be able to store it with a static lifetime and use a single reference for all comparisons.

**Comment by Diggsey** [comment]
Are there actually any `Default` implementations that allocate?

**Comment by 0x1991babe** [comment]
Good question. For reference, these were basically all added in `FetchResponse`. I'm not actually sure if the `BTreeMap` for `unknown_tagged_fields` allocates its storage on construct or only on insert.

This is mostly a reflexive tick of mine from Java of creating a bunch of trash just to do a comparison and throw away. If it's 100% on stack it might not actually be much of an optimization.

I'm going to file another issue to add benchmarks, which is probably a better way to answer these questions rather than idle speculation.

**Comment by Diggsey** [comment]
> 'm not actually sure if the BTreeMap for unknown_tagged_fields allocates its storage on construct or only on insert.

None of the `std` collections allocate on construction.

**Comment by 0x1991babe** [comment]
Awesome, good to know. This is probably a non-issue then. I also just looked at the actual instances of this in `FetchResponse`, and it seems like they all have sensible -1 default values, which answers the question from #1 of whether it's safe to use as a nil value, although probably worth keeping in mind for the future.
